# Generated by Django 5.2.4 on 2025-07-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CANCELED', 'Canceled')], default='PENDING'),
        ),
    ]
