# Generated by Django 5.2.4 on 2025-07-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component', verbose_name='Компонент')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='Описание')),
                ('components', models.ManyToManyField(related_name='products', through='products.ComponentRelation', to='components.component', verbose_name='Компоненты')),
            ],
            options={
                'verbose_name': 'Продукт (изделие)',
                'verbose_name_plural': 'Продукты (изделия)',
            },
        ),
        migrations.AddField(
            model_name='componentrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт'),
        ),
        migrations.AlterUniqueTogether(
            name='componentrelation',
            unique_together={('product', 'component')},
        ),
    ]
