# Generated by Django 5.2.4 on 2025-07-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Manual', 'Manual')], verbose_name='Тип транзакции')),
                ('item_id', models.BigIntegerField(verbose_name='Идентификатор предмета')),
                ('quantity_delta', models.IntegerField(verbose_name='Изменение количества')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('extra', models.JSONField(default={}, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Складская транзакция',
                'verbose_name_plural': 'Складские транзакции',
            },
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='id',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='pk',
            field=models.CompositePrimaryKey('warehouse_id', 'item_type', 'item_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse_id'], name='warehouses__warehou_323084_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['warehouse_id', 'item_type'], name='warehouses__warehou_98b870_idx'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип предмета'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouses.warehouse', verbose_name='Склад'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['warehouse_id'], name='warehouses__warehou_c5c932_idx'),
        ),
    ]
