# Generated by Django 5.2.4 on 2025-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_stocktransaction_remove_stockitem_id_stockitem_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='extra',
            field=models.JSONField(default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('supply', 'Supply')], verbose_name='Тип транзакции'),
        ),
    ]
