# Generated by Django 5.2.4 on 2025-07-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouses', '0003_alter_stocktransaction_extra_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['timestamp'], name='warehouses__timesta_1de4da_idx'),
        ),
    ]
